<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BusinessOS.POS.Domain\BusinessOS.POS.Domain.csproj" />
    <ProjectReference Include="..\..\src\BusinessOS.POS.Application\BusinessOS.POS.Application.csproj" />
    <ProjectReference Include="..\..\src\BusinessOS.POS.Infrastructure\BusinessOS.POS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BusinessOS.POS.LocalClient\BusinessOS.POS.LocalClient.csproj" />
    <ProjectReference Include="..\..\src\BusinessOS.POS.LocalServer\BusinessOS.POS.LocalServer.csproj" />
    <ProjectReference Include="..\..\src\BusinessOS.POS.Persistence\BusinessOS.POS.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
