namespace BusinessOS.POS.Domain.Access;

public static class PermissionCatalog
{
    public static IReadOnlyDictionary<string, string> All { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["pos.access"] = "Access POS",
            ["sales.view"] = "View sales",
            ["sales.create"] = "Create sales",
            ["sales.return"] = "Return sales",
            ["sales.void"] = "Void sales",
            ["sales.hold"] = "Hold and resume POS sales",
            ["sales.discount"] = "Apply sales discounts",
            ["sales.override_min_price"] = "Sell below configured minimum price",
            ["sales.credit"] = "Create customer credit sales",
            ["sales.override_credit_limit"] = "Override customer credit limit",
            ["purchases.view"] = "View purchases",
            ["purchases.create"] = "Create purchases",
            ["purchases.approve"] = "Approve and cancel purchase orders",
            ["purchases.receive"] = "Receive approved purchase orders",
            ["purchases.direct_receive"] = "Receive stock without a purchase order",
            ["purchases.record_payment"] = "Record initial purchase payments",
            ["purchases.return"] = "Return received purchases to suppliers",
            ["inventory.view"] = "View inventory",
            ["inventory.products.manage"] = "Create and manage products",
            ["inventory.catalog.manage"] = "Manage categories, brands and units",
            ["inventory.opening_stock"] = "Record opening stock",
            ["inventory.adjust"] = "Adjust inventory",
            ["inventory.count"] = "Perform stock counts",
            ["inventory.count.approve"] = "Approve stock counts",
            ["inventory.writeoff"] = "Post damaged and expired stock write-offs",
            ["customers.view"] = "View customers",
            ["customers.manage"] = "Manage customers",
            ["customers.quick_create"] = "Quick create customers from POS",
            ["customers.collect"] = "Record customer collections",
            ["suppliers.view"] = "View suppliers",
            ["suppliers.manage"] = "Manage suppliers",
            ["suppliers.pay"] = "Record supplier payments",
            ["expenses.view"] = "View expenses",
            ["expenses.create"] = "Create expenses and other income",
            ["cash.view"] = "View cash drawer",
            ["cash.manage"] = "Record manual cash drawer movements",
            ["reports.view"] = "View reports",
            ["reports.profit"] = "View profit reports",
            ["shifts.open"] = "Open cashier shifts",
            ["shifts.close"] = "Close cashier shifts",
            ["shifts.reopen"] = "Reopen closed shifts",
            ["business_days.view"] = "View daily closing",
            ["business_days.close"] = "Close business days",
            ["business_days.reopen"] = "Reopen business days",
            ["settings.manage"] = "Manage shop settings",
            ["users.manage"] = "Manage users and access",
            ["audit.view"] = "View audit logs",
        };
}
